server:
  port: 8888

spring:
  jpa:
    database: postgresql
    hibernate.ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://
    username:
    password: